### ISSUE TITLE
Why is there a problem?

### ISSUE THREAD

**Issue by yubau1112** [brentp/bwa-meth#61]
[yubau@CNUH-i7 ~]$ 

python /local_work/bin/bwa-meth/bwameth.py 
-t 12 
--reference /DataShare/Transcriptome/Homo_sapiens/NCBI/                                               GRCh38/Sequence/BWAIndex/version0.6.0/genome.fa.bwameth.c2t 
/home/yubau/Methylation/26-meth_S44_R1_001.fastq.gz 
/home/yubau/Methylation/26-meth_S44_R2_001.fastq.gz > /home/yubau/26-meth_S44.sam

Traceback (most recent call last):
  File "/local_work/bin/bwa-meth/bwameth.py", line 509, in <module>
    main(sys.argv[1:])
  File "/local_work/bin/bwa-meth/bwameth.py", line 506, in main
    set_as_failed=args.set_as_failed)
  File "/local_work/bin/bwa-meth/bwameth.py", line 315, in bwa_mem
    raise BWAMethException("first run bwameth.py index %s" % fa)
__main__.BWAMethException: first run bwameth.py index /DataShare/Transcriptome/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/v                                            ersion0.6.0/genome.fa.bwameth.c2t

yes i already execute "bwameth.py index $REF"

[yubau@CNUH-i7 ~]$ ls /DataShare/Transcriptome/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/version0.6.0/
genome.fa      
genome.fa.ann          
genome.fa.bwameth.c2t.amb  
genome.fa.bwameth.c2t.bwt  
genome.fa.bwameth.c2t.sa  
genome.fa.fai  genome.fa.sa
genome.fa.amb  
genome.fa.bwameth.c2t  
genome.fa.bwameth.c2t.ann  
genome.fa.bwameth.c2t.pac  
genome.fa.bwt            
 genome.fa.pac

[yubau@CNUH-i7 bwa-meth]$ ls
bam-merge-pairs.py  
bwameth.py  
compare  
example  
ez_setup.py  
LICENSE  
paper  
README.md  
requirements.txt  
scripts  
setup.py
[yubau@CNUH-i7 bwa-meth]$ pwd
/local_work/bin/bwa-meth

[yubau@CNUH-i7 bwa-meth]$ python -V
Python 2.7.15 :: Anaconda, Inc.
[yubau@CNUH-i7 bwa-meth]$ samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

[yubau@CNUH-i7 bwa-meth]$ bwa

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.17-r1188

Why is there a problem?

**Comment by brentp** [comment]
send: GRCh38/Sequence/BWAIndex/version0.6.0/genome.fa as the reference, not: GRCh38/Sequence/BWAIndex/version0.6.0/genome.fa.bwameth.c2t

**Comment by yubau1112** [comment]
[yubau@CNUH-i7 ~]$ python /local_work/bin/bwa-meth/bwameth.py -t 12 --reference /DataShare/Transcriptome/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/version0.6.0/genome.fa /home/yubau/Methylation/26-meth_S44_R1_001.fastq.gz /home/yubau/Methylation/26-meth_S44_R2_001.fastq.gz > /home/yubau/26-meth_S44.sam
running: /local_work/bin/miniconda2/bin/python /local_work/bin/bwa-meth/bwameth.py c2t /home/yubau/Methylation/26-meth_S44_R1_001.fastq.gz /home/yubau/Methylation/26-meth_S44_R2_001.fastq.gz |bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:26-meth_S44_R_001\tSM:26-meth_S44_R_001' -t 12  /DataShare/Transcriptome/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/version0.6.0/genome.fa.bwameth.c2t -
Traceback (most recent call last):
  File "/local_work/bin/bwa-meth/bwameth.py", line 509, in <module>
    main(sys.argv[1:])
  File "/local_work/bin/bwa-meth/bwameth.py", line 506, in main
    set_as_failed=args.set_as_failed)
  File "/local_work/bin/bwa-meth/bwameth.py", line 331, in bwa_mem
    as_bam(cmd, fa, set_as_failed)
  File "/local_work/bin/bwa-meth/bwameth.py", line 341, in as_bam
    sam_iter = nopen_keep_parent_stdin(pfile, 'r')
  File "/local_work/bin/bwa-meth/bwameth.py", line 49, in nopen_keep_parent_stdin
    preexec_fn=toolshed.files.prefunc,
AttributeError: 'module' object has no attribute 'prefunc'

**Comment by yubau1112** [comment]
still can not working

[yubau@CNUH-i7 bwa-meth]$ ls
26-meth_S44.sam     compare      genome.fa                  genome.fa.bwameth.c2t.ann  genome.fa.bwameth.c2t.sa  README.md         setup.py
bam-merge-pairs.py  example      genome.fa.bwameth.c2t      genome.fa.bwameth.c2t.bwt  LICENSE                   requirements.txt  toolshed-0.4.0
bwameth.py          ez_setup.py  genome.fa.bwameth.c2t.amb  genome.fa.bwameth.c2t.pac  paper                     scripts           toolshed-0.4.0.tar.gz

[yubau@CNUH-i7 bwa-meth]$ bwameth.py -t 12 --reference genome.fa.bwameth.c2t /home/yubau/Methylation/sample_test_1.fastq /home/yubau/Methylation/sample_test_2.fastq > sample_test.sam
Traceback (most recent call last):
  File "/local_work/bin/miniconda2/bin/bwameth.py", line 4, in <module>
    __import__('pkg_resources').run_script('bwameth==0.2.2', 'bwameth.py')
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py", line 509, in <module>
    main(sys.argv[1:])
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py", line 506, in main
    set_as_failed=args.set_as_failed)
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py", line 315, in bwa_mem
    raise BWAMethException("first run bwameth.py index %s" % fa)
__main__.BWAMethException: first run bwameth.py index genome.fa.bwameth.c2t

**Comment by yubau1112** [comment]
[yubau@CNUH-i7 bwa-meth]$ ls
26-meth_S44.sam     compare      genome.fa                  genome.fa.bwameth.c2t.ann  genome.fa.bwameth.c2t.sa  README.md         scripts         toolshed-0.4.0.tar.gz
bam-merge-pairs.py  example      genome.fa.bwameth.c2t      genome.fa.bwameth.c2t.bwt  LICENSE                   requirements.txt  setup.py
bwameth.py          ez_setup.py  genome.fa.bwameth.c2t.amb  genome.fa.bwameth.c2t.pac  paper                     sample_test.sam   toolshed-0.4.0


[yubau@CNUH-i7 bwa-meth]$ bwameth.py -t 12 --reference genome.fa /home/yubau/Methylation/sample_test_1.fastq /home/yubau/Methylation/sample_test_2.fastq > sample_test.sam


running: /local_work/bin/miniconda2/bin/python /local_work/bin/miniconda2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py c2t /home/yubau/Methylation/sample_test_1.fastq /home/yubau/Methylation/sample_test_2.fastq |bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:sample_test_\tSM:sample_test_' -t 12  genome.fa.bwameth.c2t -
Traceback (most recent call last):
  File "/local_work/bin/miniconda2/bin/bwameth.py", line 4, in <module>
    __import__('pkg_resources').run_script('bwameth==0.2.2', 'bwameth.py')
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py", line 509, in <module>
    main(sys.argv[1:])
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py", line 506, in main
    set_as_failed=args.set_as_failed)
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py", line 331, in bwa_mem
    as_bam(cmd, fa, set_as_failed)
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py", line 341, in as_bam
    sam_iter = nopen_keep_parent_stdin(pfile, 'r')
  File "/local_work/bin/miniconda2/lib/python2.7/site-packages/bwameth-0.2.2-py2.7.egg/EGG-INFO/scripts/bwameth.py", line 49, in nopen_keep_parent_stdin
    preexec_fn=toolshed.files.prefunc,
AttributeError: 'module' object has no attribute 'prefunc'
