### ISSUE TITLE
MAPQ0 due to secondary alignment in alt contigs

### ISSUE THREAD

**Issue by yangruialex** [brentp/bwa-meth#65]
I have encountered an issue where alignments have 0 MAPQ because of secondary alignments in alt contigs. This is usually fixed by bwa-postalt for regular DNA sequencing but it does not seem to work for bwa meth.

For example all alignments in chr1:155,252,932-155,257,513 have MAPQ of 0 with bwa meth but MAPQ60 with bwa mem.

Any thoughts?

**Comment by yangruialex** [comment]
pUpdate: the alt handling happens during `bwa mem` with a defined `.alt` file. I have tried to make a custom `alt` file for the C to T converted reference (by adding the f and r prefix to contig names) but that caused the following error:
```[M::bwa_idx_load_from_disk] read 5292 ALT contigs
Traceback (most recent call last):
  File "/home/ryang/miniconda/envs/balrog/bin/bwameth.py", line 4, in <module>
    __import__('pkg_resources').run_script('bwameth==0.2.2', 'bwameth.py')
  File "/home/ryang/miniconda/envs/balrog/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ryang/miniconda/envs/balrog/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/home/ryang/miniconda/envs/balrog/lib/python3.6/site-packages/bwameth-0.2.2-py3.6.egg-info/scripts/bwameth.py", line 509, in <module>
    main(sys.argv[1:])
  File "/home/ryang/miniconda/envs/balrog/lib/python3.6/site-packages/bwameth-0.2.2-py3.6.egg-info/scripts/bwameth.py", line 506, in main
    set_as_failed=args.set_as_failed)
  File "/home/ryang/miniconda/envs/balrog/lib/python3.6/site-packages/bwameth-0.2.2-py3.6.egg-info/scripts/bwameth.py", line 331, in bwa_mem
    as_bam(cmd, fa, set_as_failed)
  File "/home/ryang/miniconda/envs/balrog/lib/python3.6/site-packages/bwameth-0.2.2-py3.6.egg-info/scripts/bwameth.py", line 345, in as_bam
    handle_header(line)
  File "/home/ryang/miniconda/envs/balrog/lib/python3.6/site-packages/bwameth-0.2.2-py3.6.egg-info/scripts/bwameth.py", line 359, in handle_header
    sq, sn, ln = toks  # @SQ    SN:fchr11    LN:122082543
ValueError: too many values to unpack (expected 3)
```

So far my workaround for this is to use a reference that has the alt contigs removed.

**Comment by brentp** [comment]
not sure how this:
```
  File "/home/ryang/miniconda/envs/balrog/lib/python3.6/site-packages/bwameth-0.2.2-py3.6.egg-info/scripts/bwameth.py", line 359, in handle_header
    sq, sn, ln = toks  # @SQ    SN:fchr11    LN:122082543
ValueError: too many values to unpack (expected 3)
```
is happening. you could use `sq, sn, ln = toks[0:3]` to truncate the extra stuff (assuming the order is maintained).
