### ISSUE TITLE
Timestamp checking of .fa files prevents me from running  bwa-meth in the cloud

### ISSUE THREAD

**Issue by jnthnhss** [brentp/bwa-meth#83]
I'm running bwa-meth in the cloud and have therefore no control over the timestamps of the .fa and related files. That is, the converted the .fa file via `bwameth.py index-mem2`, uploaded them in the correct order (that is, uploading the .fa file first) and still I have the problem that bwa-meth.py complains that
> the modification time on the generated c2t files is newer than on the .fa file
Post-hoc manipulation of timestamps via `touch` is also unsuccessful. Would it be possible to disable checking the modification timestamps or have a flag for this?

**Comment by brentp** [comment]
yeah. that's not good. 
can you share the full command that you are running and the full stderr+stdout?

**Comment by jnthnhss** [comment]
Full stderr+stdout is difficult because the logs are accessed via Splunk

```
bwameth.py --threads 36 --reference /reference/bwa-meth/GRCh38.d1.vd1/GRCh38.d1.vd1.fa T_1_trimmed.fq.gz T_2_trimmed.fq.gz
```

```
File "/opt/bin/bwameth.py", line 550, in main
File "/opt/bin/bwameth.py", line 559, in <module> 
bwa_mem(args.reference, conv_fqs_cmd, ' '.join(map(str, pass_through_args)),
main(sys.argv[1:])
Traceback (most recent call last):
File "/opt/bin/bwameth.py", line 349, in bwa_mem
  raise BWAMethException("first run bwameth.py index %s OR bwameth.py index-mem2 %s" % (fa, fa))
  __main__.BWAMethException: first run bwameth.py index /reference/bwa-meth/GRCh38.d1.vd1/GRCh38.d1.vd1.fa OR bwameth.py index-mem2 /reference/bwa-meth/GRCh38.d1.vd1/GRCh38.d1.vd1.fa
```

The problem is that /reference is a read-only mounted image. I can therefore not manipulate the .fa file timestamp via
```
touch -t 202001010000 /reference/bwa-meth/GRCh38.d1.vd1/GRCh38.d1.vd1.fa
```

**Comment by mbeavitt** [comment]
Was there every any resolution of this?

**Comment by brentp** [comment]
I tagged v0.2.9 with these changes
