### ISSUE TITLE
Exception("bad or empty fastqs")

### ISSUE THREAD

**Issue by kea027** [brentp/bwa-meth#91]
I have confirmed my fastq files are accurate but bwa-meth is pulling the raise Exception("bad or empty fastqs").  It seems to pull this exception right at the end of the alignment.  Is there a method to fix this error?

**Comment by brentp** [comment]
it seems that you have no alignments. Can you show the first few and last few lines of your fastqs and the full stderr of the bwameth run?

**Comment by kea027** [comment]
stderr:
M::mem_process_seqs] Processed 1649302 reads in 1529.820 CPU sec, 848.893 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R @RG\tID:RVF_36hr_S4_R_001_val_\tSM:RVF_36hr_S4_R_001_val_ -t 30 -o /PATH/RVF_36hr_S4_methylome_new.bam References/Chlorocebus_sabaeus.ChlSab1.1.dna.toplevel.fa.bwameth.c2t /dev/stdin
[main] Real time: 51218.648 sec; CPU: 92491.098 sec
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/methylation/bin/bwameth.py", line 563, in <module>
    main(sys.argv[1:])
  File "/home/user/anaconda3/envs/methylation/bin/bwameth.py", line 559, in main
    do_not_penalize_chimeras=args.do_not_penalize_chimeras)
  File "/home/user/anaconda3/envs/methylation/bin/bwameth.py", line 370, in bwa_mem
    as_bam(cmd, fa, set_as_failed, do_not_penalize_chimeras)
  File "/home/user/anaconda3/envs/methylation/bin/bwameth.py", line 387, in as_bam
    raise Exception("bad or empty fastqs")
Exception: bad or empty fastqs

Fastq files head/tails 
R1: head 
@VL00388:12:AACT2TTM5:1:1101:18421:1000 1:N:0:CCAGTATC+ATCTCGCT
GTTGTATAAATATTTATTATAGTTTTTATTTTTAATTTTTTTGGGTAAATATTTAGAAGTAGAAGTATTAGATTATATAGTAATTTTGTTTAATTTTTTGAAGAATTTTTTATTATATTATTATTTATGTTAGTTTATATTTTTATTAGT
+
CCCCCCCCC;C-CCC;CCCCCCCCCCCCCCC-CC-CCCCCCCCCCCC--CCCCCCCC-;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCCCCCC-CCCCCC-;C;CCCCCCCCCCCCC
@VL00388:12:AACT2TTM5:1:1101:18875:1000 1:N:0:CCAGTATC+ATCTCGCT
GGTCGGGAGGACGTTTTTGGTTCGGCGTTGTTTCGGCGTGTGTTTTGGGGTCGATTAGAGGGTTTTGGGTGTTTTGTGTTTGGTTGCGATGGTGGTGATTTTGGGGATAGATGTTCGTGTCGCGGGTTTTTTGGGTCGGCGGCGTGGTC
+
C;C;CCCCCCCCC-CCCCCCCCC;CCCCCCCCCCCCCCCCCCC-CCCCCCCCC--CC;-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCC-CCCCCCC;CCCCCCCCC;CCCCCCCCCCCCCCCC-CCCCCC
@VL00388:12:AACT2TTM5:1:1101:19027:1000 1:N:0:CCAGTATC+ATCTCGCT
TTATTGAAAAGGTGAATAAATATTTTATTATTTTTTGTTAGTGTTATATGAAAATTTTGTTTAAAAGAGAAAATTAAATTGTATTTTTTTTTAGTGTATTATTAATATTAAAGTTAATTTAATAAAATATTATAAATAAATTTCTTTAATT

R1 tail: 
+
CCCCCC;CCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCC-;--C-C;C-C-CCCCCC;;CC;CCC-CC-CCCC--C-CCC-CCCC-C--C;CC--C-CCCCC-CCC-CCCC;C
@VL00388:12:AACT2TTM5:1:2611:65267:56394 1:N:0:CCAGTATC+ATCTCGCT
GAGGTGTTTAATTTGGTTATGTAGAATGTAGTTGGGTTGTTTGAAATGAAATAAAGTGGTTATTTTGAAGGAGGTGTTGTTTTTGGGTTGGTTTAGGTTGAGTTAGAGTAGATGTTATTTTTATGTTA
+
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCC;CCCCCCCCCCCCCCCCCC;;-CCCCCCCCCCCCCCCCCCC-CCCCCCCCCCC;CCCCCCCCCCCCCCCCCCC;CCCC-CCCCCCCCCC
@VL00388:12:AACT2TTM5:1:2611:65381:56394 1:N:0:CCAGTATC+ATCTCGCT
TTAGTTTTTTTATAGTTATTAGTGAATGTTTTGTTTGATGTTTTTAGATGTTAGTTTGGGTGTAGGTTGGTTTTGGGAGTTAGTTTTAGAGTTTGTTATTTAAGTTTATTTAATTTGTTGATATGTTTGTTTTTGGAGTTTTTATTTTT
+
C;CCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCC;CCCCCCCCCCCCCC;-CC-CCCC-C--C;CC;;CCC-CCCCCC;CCCCC--CCC-CCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

R2 head: @VL00388:12:AACT2TTM5:1:1101:18421:1000 2:N:0:CCAGTATC+ATCTCGCT
CATCAAAAACCATTTAACACATTACTTAAATCAATTAAAACCTTTATATACTACTAATAAAAATATAAACTAACATAAATAATAATATNATAAAAAATTCTTCAAAAAATTAAACAAAATTACTATATAATCTAAATCTTCTACTTCTA
+
CCCCCCCCC-CCCCCCCCCCC;CCC;CCC-CC-CCCCCC-CCCCC-C;CC;CCCCCCC-;CC-CCC;;-C---C--;CCCC-CCC;CC#CCC;---CCCCCCC-;;CC-;C;C-CCCC;-CCC;;C-;-;CC-C;--;C-C;-CCCCCC
@VL00388:12:AACT2TTM5:1:1101:18875:1000 2:N:0:CCAGTATC+ATCTCGCT
TCTCCAACGACAAGTCGCCAAAAAACAACGTATCAACAATAACCCGATAACCCAAAATACCGACTCGAAATAAAAAATATTCCTCCCCNAAAAACAAAAAATCGAACCTCCGACCACGCCGCCGACCCAAAAAACCCGCGACTCGAACATC
+
CCCCCC;;C-CCCCCCCCCCCC;CCCCCCCC;CC;C;--C-CCCCCC;C-C;CC;-C;-CCCC;CCCCCCC--CC-;CCC;-CC;CC-#;-C;-CC;C;-;CCCCCCC-;;CCCC-CCC;C--CC-;--C-CC--C-;C;CC-C;---C-C
@VL00388:12:AACT2TTM5:1:1101:19027:1000 2:N:0:CCAGTATC+ATCTCGCT
TTAAATTAAAAAAATAAAAAAAAATAACAAAAAAAACTAAATAAATATAAAAAATTACAAAAAAAAAAAAAATTAAAAAAATTTTTAANAATTTTTTCGTATTGTTATAATTCTTTTGTATTATATCATCTATTTTTATTTTAATAT

 R2 tail: 
+
CCC;CCCCCCCCCC;-CCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCC-CCC;C;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;C-CCCCCC;CCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCC;--CCCC--CCCC--C--
@VL00388:12:AACT2TTM5:1:2611:65267:56394 2:N:0:CCAGTATC+ATCTCGCT
TTAACATAAAAATAACATCTACTCTAACTCAACCTAAACCAACCCAAAAACAACACCTCCTTCAAAATAACCACTTTATTTCATTTCAAACAACCCAACTACATTCTACATAACCAAATTAAACACCTC
+
CCCCCCCCCCCCC-CCCCCCCCCCC-;CCCCCCCCCC-CCCCCCCC;CC;CCC;---CCC;CCCC;CCCCCC;;CCCCC;CC-CCCCC-CC;C;CCC;CC-CC;CCCCCCC-CCCCC;CC;CCC-;CCC
@VL00388:12:AACT2TTM5:1:2611:65381:56394 2:N:0:CCAGTATC+ATCTCGCT
TACCCACGATACGTATATCAACAAAATATTTAACGAAAATAACAACCAAACGAATCAAAATCTCTTCATAACCTACAAAAATAAAAATTAAAACGTATTTACTAAAAATAAAAACTCCAAAAACAAACATATCAACAAATTAAATAACAT
+
CCCCCCCCCCCCCCCC-CCC-;-CC;CC;CC;CCCCCCCCCC-CCCCCC-CCC;CC;C-;CCCCCCCCCCCCCCCCC-CCCC-CCCCC-CCCCCC-CC--C;CCCCC;CCCC;-CCCC-CCCCC-C-;----C--C-C;CCCCC;--C-C
