### ISSUE TITLE
ERROR! Unable to open the file: */GRCh38.p7.genome.fa.bwameth.c2t.bwt.2bit.64

### ISSUE THREAD

**Issue by Wong718** [brentp/bwa-meth#96]
Hello, It's a wonderful and user-friendly tool for methylation detection.
Here is an issue when applying the alignment step.
```bash
---------------------
Found BWA MEM2 index
running: /dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/python /dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py c2t ./test_data/SRR10532142_R1.filtered.fastq.gz ./test_data/SRR10532142_R2.filtered.fastq.gz |bwa-mem2 mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:SRR10532142_R.filtered\tSM:SRR10532142_R.filtered' -t 6  /dshare/home/wangzj/3DGenome/ref_genome/GRCh38.p7.genome.fa.bwameth.c2t /dev/stdin
--------------------
Looking to launch executable "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwa-mem2.avx512bw", simd = .avx512bw
Launching executable "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwa-mem2.avx512bw"
converting reads in ./test_data/SRR10532142_R1.filtered.fastq.gz,./test_data/SRR10532142_R2.filtered.fastq.gz
-----------------------------
Executing in AVX512 mode!!
-----------------------------
* SA compression enabled with xfactor: 8
* Ref file: /dshare/home/wangzj/3DGenome/ref_genome/GRCh38.p7.genome.fa.bwameth.c2t
* Entering FMI_search
ERROR! Unable to open the file: /dshare/home/wangzj/3DGenome/ref_genome/GRCh38.p7.genome.fa.bwameth.c2t.bwt.2bit.64
Traceback (most recent call last):
  File "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py", line 563, in <module>
    main(sys.argv[1:])
  File "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py", line 519, in main
    sys.exit(convert_reads(args[1], args[2]))
  File "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py", line 144, in convert_reads
    convert_and_write_read(name,seq,qual,read_i%2,out)
  File "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py", line 177, in convert_and_write_read
    out.write("".join((name, seq, "\n+\n", qual)))
BrokenPipeError: [Errno 32] Broken pipe
cmd was:/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/python /dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py c2t ./test_data/SRR10532142_R1.filtered.fastq.gz ./test_data/SRR10532142_R2.filtered.fastq.gz |bwa-mem2 mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:SRR10532142_R.filtered\tSM:SRR10532142_R.filtered' -t 6  /dshare/home/wangzj/3DGenome/ref_genome/GRCh38.p7.genome.fa.bwameth.c2t /dev/stdin
return code was:1
Traceback (most recent call last):
  File "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py", line 563, in <module>
    main(sys.argv[1:])
  File "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py", line 554, in main
    bwa_mem(args.reference, conv_fqs_cmd, ' '.join(map(str, pass_through_args)),
  File "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py", line 370, in bwa_mem
    as_bam(cmd, fa, set_as_failed, do_not_penalize_chimeras)
  File "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py", line 382, in as_bam
    for line in sam_iter:
  File "/dshare/home/wangzj/env_set/miniconda3/envs/env_nf/lib/python3.8/site-packages/toolshed/files.py", line 61, in process_iter
    raise ProcessException(cmd)
toolshed.files.ProcessException: /dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/python /dshare/home/wangzj/env_set/miniconda3/envs/env_nf/bin/bwameth.py c2t ./test_data/SRR10532142_R1.filtered.fastq.gz ./test_data/SRR10532142_R2.filtered.fastq.gz |bwa-mem2 mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:SRR10532142_R.filtered\tSM:SRR10532142_R.filtered' -t 6  /dshare/home/wangzj/3DGenome/ref_genome/GRCh38.p7.genome.fa.bwameth.c2t /dev/stdin
```
The index files generated in the last step were
```bash
GRCh38.p7.genome.fa.bwameth.c2t.0123
GRCh38.p7.genome.fa.bwameth.c2t.amb
GRCh38.p7.genome.fa.bwameth.c2t.ann
GRCh38.p7.genome.fa.bwameth.c2t.pac
GRCh38.p7.genome.fa.bwameth.c2t
```
Could you help me to figure it out? thx.

**Comment by brentp** [comment]
hi, are you sure you indexed with bwa mem2? it looks like you indexed only with bwa mem
